import { mkdir, readFile, rename, rm, writeFile } from 'node:fs/promises';
import { dirname, join, resolve, sep } from 'node:path';
import { randomUUID } from 'node:crypto';

export interface ArtifactStore {
  put(key: string, bytes: Buffer): Promise<void>;
  get(key: string): Promise<Buffer>;
  delete(key: string): Promise<void>;
}

/**
 * Persistent local artifact implementation for the self-host beta. Keys are
 * generated by trusted server code; path resolution still rejects traversal so
 * future callers cannot turn this seam into arbitrary filesystem access.
 */
export class LocalArtifactStore implements ArtifactStore {
  private readonly root: string;

  constructor(root: string) {
    this.root = resolve(root);
  }

  async put(key: string, bytes: Buffer): Promise<void> {
    const path = this.pathFor(key);
    await mkdir(dirname(path), { recursive: true, mode: 0o700 });
    const temporary = `${path}.${randomUUID()}.tmp`;
    await writeFile(temporary, bytes, { mode: 0o600, flag: 'wx' });
    await rename(temporary, path);
  }

  get(key: string): Promise<Buffer> {
    return readFile(this.pathFor(key));
  }

  async delete(key: string): Promise<void> {
    await rm(this.pathFor(key), { force: true });
  }

  private pathFor(key: string): string {
    if (!/^[a-f0-9-]{36}\/[a-f0-9-]{36}\.(png|webp)$/.test(key)) {
      throw new Error('invalid artifact key');
    }
    const path = resolve(join(this.root, key));
    if (!path.startsWith(`${this.root}${sep}`)) throw new Error('artifact path escapes root');
    return path;
  }
}
